media-user-token: "your-media-user-token"
embed-lrc: true
save-lrc-file: false
embed-cover: true
cover-size: 5000x5000
cover-format: jpg       #jpg or png
alac-save-folder: AM-DL downloads
atmos-save-folder: AM-DL-Atmos downloads
check: ""
force-api: false
get-m3u8-from-device: false
alac-max: 192000  #192000 96000 48000 44100
atmos-max: 2768  #2768 2448
#{AlbumId} {AlbumName} {ArtistName} {ReleaseDate} {ReleaseYear} {UPC} {Copyright} {Quality}
#example: {ReleaseYear} - {ArtistName} - {AlbumName}({AlbumId})({UPC})({Copyright})
album-folder-format: "{AlbumName}"
#{PlaylistId} {PlaylistName} {ArtistName} {Quality}
playlist-folder-format: "{PlaylistName}"
#{SongId} {SongNumer} {SongName} {DiscNumber} {TrackNumber} {Quality}
#example: Disk {DiscNumber} - Track {TrackNumber} {SongName} [{Quality}]"
song-file-format: "{SongNumer}. {SongName}"
#{ArtistId} {ArtistName}
#if artist-folder-format set "",will not make artist folder
artist-folder-format: "{ArtistName}"
#if set "" will not add tag
explicit-choice : "[E]"
clean-choice : "[C]"
apple-master-choice : "[M]"
#if set true,Quality will change to [ALAC 24B-96.0kHz] [Atmos 768kbps]
add-codec: false
