name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        go build -o main.exe -v ./main.go
        go build -o main_atmos.exe -v ./main_atmos.go
        go build -o main_select.exe -v ./main_select.go
    - name: Create a new directory and copy files
      run: |
        mkdir -p alac
        cp agent.js alac/
        cp config.yaml alac/
        cp main.exe alac/
        cp main_atmos.exe alac/
        cp main_select.exe alac/

    - name: Upload apple-music-alac-atmos-downloader
      uses: actions/upload-artifact@v2
      with:
        name: apple-music-alac-atmos-downloader
        path: alac/*